version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: cimg/postgres:14.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: sweater-weather_test
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true
      - run: bundle install # run the `bundle install` command
      # - save_cache:
      #     key: sweater-weather-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - vendor/bundle
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load
      - run: bundle exec rspec # run the `rspec` test suite
