version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: bundle install # run the `bundle install` command
      - run: bundle exec rspec # run the `rspec` test suite
