version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
            
      - image: cimg/postgres:14.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
      - run: bundle install # run the `bundle install` command

      - run:
        name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load
      - run: bundle exec rspec # run the `rspec` test suite
